# Movies processing
Processing the `ratings.csv.` dataset so that each row of the Dataframe is an user and each column is a movie with the rating of the movie from the user.

In [1]:
import pandas as pd
import numpy as np

ratings_dataset = pd.read_csv('ratings.csv')
movies_dataset = pd.read_csv('movies.csv')
movies_ids = movies_dataset['movieId'].to_list()


def procress_dataset():
  proccessed_dataset = pd.DataFrame([], columns=movies_ids)
  users = ratings_dataset['userId'].unique()

  for userId in users:
    print(userId)
    user_ratings = ratings_dataset[ratings_dataset['userId'] == userId]
    user_ratings = user_ratings[['movieId', 'rating']]
    user_ratings.set_index('movieId',inplace=True)
    user_ratings = user_ratings.T
    
    new_user = []
    def adjust_rating(rating):
      return ((10 * rating) - 30)

    for movie in movies_ids:
      try:
        new_user.append(adjust_rating(user_ratings.iloc[0][movie]))
      except:
        new_user.append(0)

    proccessed_dataset.loc[len(proccessed_dataset.index)] = new_user
    
  compression_opts = dict(method='zip', archive_name='processed.csv')  
  proccessed_dataset.to_csv('processed.zip', index=False, compression=compression_opts)
  proccessed_dataset.to_pickle('processed.pkl')
  proccessed_dataset.reset_index()

  return proccessed_dataset

df = procress_dataset()
# df = pd.read_pickle('processed.pkl')
# df.drop([213,  53,  25, 162, 608, 190, 502, 500, 287, 286, 498], inplace=True)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


The column names are the movie ids.
An adjustment to the movie rating was made such that a score of 3 is mapped to 0 (zero) and the rating was then. Scores below 3 and negative scores.

In [19]:
display(df)

1       2       3       4       5       6       7       8       9       \
0      10.0     0.0    10.0     0.0     0.0    10.0     0.0     0.0     0.0   
1       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4      10.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
605    -5.0     0.0     0.0     0.0     0.0     0.0    -5.0     0.0     0.0   
606    10.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
607    -5.0   -10.0   -10.0     0.0     0.0     0.0     0.0     0.0     0.0   
608     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
609    20.0     0.0     0.0     0.0     0.0    20.0     0.0     0.0     0.0   

     10      ...  193565  193567  193571  193573  193579  193581  193583  \
0       0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1       0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2       0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3       0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4       0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
605     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
606     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
607    10.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
608    10.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
609     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

     193585  193587  193609  
0       0.0     0.0     0.0  
1       0.0     0.0     0.0  
2       0.0     0.0     0.0  
3       0.0     0.0     0.0  
4       0.0     0.0     0.0  
..      ...     ...     ...  
605     0.0     0.0     0.0  
606     0.0     0.0     0.0  
607     0.0     0.0     0.0  
608     0.0     0.0     0.0  
609     0.0     0.0     0.0  

[610 rows x 9742 columns]

# Nearest neighbors
For the recomendation system the nearest neighbor model was used to provide an user with new movies to watch. These new movies are from the account of the user that is closest to the user asking for recomendations based on their reviews. The movies are then sorted by the rating the user that being used as a recomendation gave the movies. 

In [20]:
def nn_recomendations(user):
  display(user)
  from sklearn.neighbors import NearestNeighbors
  nbrs = NearestNeighbors(n_neighbors=5).fit(df)
  _, indices = nbrs.kneighbors(user)
  nearest_user = indices[0][0]

  display('Nearest', indices)
  
  def get_recs():
    recs = []
    for near_user in indices[0]:
      for movie in movies_ids:
        if (df.iloc[near_user].at[movie] > 0):
          recs.append((movie, df.iloc[nearest_user].at[movie]))
    return recs
    
  recs = get_recs()
  sorted_recs = sorted(recs, key=lambda x: x[1], reverse=True)
        
  return sorted_recs


In [21]:
user = df.sample()
display(df.sample())
recs = nn_recomendations(df.sample())

for rec in recs[:10]:
  title = movies_dataset[movies_dataset['movieId'] == rec[0]]['title']
  display(str(title))

1       2       3       4       5       6       7       8       9       \
569    10.0     5.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

     10      ...  193565  193567  193571  193573  193579  193581  193583  \
569     5.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

     193585  193587  193609  
569     0.0     0.0     0.0  

[1 rows x 9742 columns]

1       2       3       4       5       6       7       8       9       \
486     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

     10      ...  193565  193567  193571  193573  193579  193581  193583  \
486     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

     193585  193587  193609  
486     0.0     0.0     0.0  

[1 rows x 9742 columns]

'Nearest'

array([[486, 213,  53, 179, 162]])

'5664    Battlestar Galactica (2003)\nName: title, dtype: object'

'8569    The Imitation Game (2014)\nName: title, dtype: object'

'224    Star Wars: Episode IV - A New Hope (1977)\nName: title, dtype: object'

'686    Rear Window (1954)\nName: title, dtype: object'

'899    Princess Bride, The (1987)\nName: title, dtype: object'

'2226    Fight Club (1999)\nName: title, dtype: object'

'3194    Shrek (2001)\nName: title, dtype: object'

'3562    Donnie Darko (2001)\nName: title, dtype: object'

'3638    Lord of the Rings: The Fellowship of the Ring,...\nName: title, dtype: object'

'4137    Lord of the Rings: The Two Towers, The (2002)\nName: title, dtype: object'

In [22]:
zero = df.sample()
for col in zero.columns:
  zero[col] = 0

# Artsy

In [23]:
import random

black_swan = 81591
twelve_angry_men = 1203
ikiru = 6669
american_history_x = 2329
gattaca = 1653
a_clockwork_orange = 1206
donnie_darko = 4878
harakiri = 26082
silence_of_the_lamb = 593
beautiful_mind = 4995
rain_man = 1961
whiplash = 112552
let_the_right_one_in = 61240
goodnight_mommy = 139655
run_lola_run = 2692
pans_labyrinth = 48394

artsy = zero.copy()
artsy[black_swan] = random.randint(10, 30)
artsy[twelve_angry_men] = random.randint(10, 30)
artsy[ikiru] = random.randint(10, 30)
artsy[american_history_x] = random.randint(10, 30)
artsy[gattaca] = random.randint(10, 30)
artsy[a_clockwork_orange] = random.randint(10, 30)
artsy[donnie_darko] = random.randint(10, 30)
artsy[harakiri] = random.randint(10, 30)
artsy[silence_of_the_lamb] = random.randint(10, 30)
artsy[beautiful_mind] = random.randint(10, 30)
artsy[rain_man] = random.randint(10, 30)
artsy[whiplash] = random.randint(10, 30)
artsy[let_the_right_one_in] = random.randint(10, 30)
artsy[goodnight_mommy] = random.randint(10, 30)
artsy[run_lola_run] = random.randint(10, 30)
artsy[pans_labyrinth] = random.randint(10, 30)

display(artsy)

recs = nn_recomendations(artsy)

for rec in recs:
  title = movies_dataset[movies_dataset['movieId'] == rec[0]]['title']
  display(str(title))


1       2       3       4       5       6       7       8       9       \
502       0       0       0       0       0       0       0       0       0   

     10      ...  193565  193567  193571  193573  193579  193581  193583  \
502       0  ...       0       0       0       0       0       0       0   

     193585  193587  193609  
502       0       0       0  

[1 rows x 9742 columns]

1       2       3       4       5       6       7       8       9       \
502       0       0       0       0       0       0       0       0       0   

     10      ...  193565  193567  193571  193573  193579  193581  193583  \
502       0  ...       0       0       0       0       0       0       0   

     193585  193587  193609  
502       0       0       0  

[1 rows x 9742 columns]

'Nearest'

array([[ 53,  25, 213, 292, 193]])

'277    Shawshank Redemption, The (1994)\nName: title, dtype: object'

'314    Forrest Gump (1994)\nName: title, dtype: object'

'510    Silence of the Lambs, The (1991)\nName: title, dtype: object'

'510    Silence of the Lambs, The (1991)\nName: title, dtype: object'

'510    Silence of the Lambs, The (1991)\nName: title, dtype: object'

'43    Seven (a.k.a. Se7en) (1995)\nName: title, dtype: object'

'138    Die Hard: With a Vengeance (1995)\nName: title, dtype: object'

'257    Pulp Fiction (1994)\nName: title, dtype: object'

'395    Firm, The (1993)\nName: title, dtype: object'

'398    Fugitive, The (1993)\nName: title, dtype: object'

'509    Batman (1989)\nName: title, dtype: object'

"809    William Shakespeare's Romeo + Juliet (1996)\nName: title, dtype: object"

'1258    Boogie Nights (1997)\nName: title, dtype: object'

'1267    Truman Show, The (1998)\nName: title, dtype: object'

'140    First Knight (1995)\nName: title, dtype: object'

'274    Specialist, The (1994)\nName: title, dtype: object'

"300    Muriel's Wedding (1994)\nName: title, dtype: object"

'484    Three Musketeers, The (1993)\nName: title, dtype: object'

'792    Sound of Music, The (1965)\nName: title, dtype: object'

'829    Platoon (1986)\nName: title, dtype: object'

'951    Chinatown (1974)\nName: title, dtype: object'

'987    This Is Spinal Tap (1984)\nName: title, dtype: object'

'1076    Sneakers (1992)\nName: title, dtype: object'

'1146    Grosse Pointe Blank (1997)\nName: title, dtype: object'

'1243    Gattaca (1997)\nName: title, dtype: object'

'1806    Romancing the Stone (1984)\nName: title, dtype: object'

'2027    Arachnophobia (1990)\nName: title, dtype: object'

'3673    M*A*S*H (a.k.a. MASH) (1970)\nName: title, dtype: object'

'4795    Last Samurai, The (2003)\nName: title, dtype: object'

In [24]:
import random

terminator_1 = 1240 
terminator_2 = 589
the_dark_knight = 58559
fast_furious_1 = 4369
fast_furious_2 = 46335
fast_furious_4 = 67923
fast_furious_5 = 86644
fast_furious_6 = 102716
fast_furious_7 = 130634
fast_furious_8 = 170875
scott_pilgrim = 79702
avengers = 89745
avengers_the_age_of_ultron = 122892
avengers_infinity = 122912
tropical_thunder = 61132
resident_evil_1 = 5219
resident_evil_2 = 8861 


action = zero.copy()
action[terminator_1] = random.randint(10, 30)
action[terminator_2] = random.randint(10, 30)
action[the_dark_knight] = random.randint(10, 30)
action[fast_furious_1] = random.randint(10, 30)
action[fast_furious_2] = random.randint(10, 30)
action[fast_furious_4] = random.randint(10, 30)
action[fast_furious_5] = random.randint(10, 30)
action[fast_furious_6] = random.randint(10, 30)
action[fast_furious_7] = random.randint(10, 30)
action[fast_furious_8] = random.randint(10, 30)
action[scott_pilgrim] = random.randint(10, 30)
action[avengers] = random.randint(10, 30)
action[avengers_the_age_of_ultron] = random.randint(10, 30)
action[avengers_infinity] = random.randint(10, 30)
action[tropical_thunder] = random.randint(10, 30)
action[resident_evil_1] = random.randint(10, 30)
action[resident_evil_2] = random.randint(10, 30)

display(action)

recs = nn_recomendations(action)

for rec in recs:
  title = movies_dataset[movies_dataset['movieId'] == rec[0]]['title']
  display(str(title))

1       2       3       4       5       6       7       8       9       \
502       0       0       0       0       0       0       0       0       0   

     10      ...  193565  193567  193571  193573  193579  193581  193583  \
502       0  ...       0       0       0       0       0       0       0   

     193585  193587  193609  
502       0       0       0  

[1 rows x 9742 columns]

1       2       3       4       5       6       7       8       9       \
502       0       0       0       0       0       0       0       0       0   

     10      ...  193565  193567  193571  193573  193579  193581  193583  \
502       0  ...       0       0       0       0       0       0       0   

     193585  193587  193609  
502       0       0       0  

[1 rows x 9742 columns]

'Nearest'

array([[ 53, 213,  25, 162, 608]])

'277    Shawshank Redemption, The (1994)\nName: title, dtype: object'

'314    Forrest Gump (1994)\nName: title, dtype: object'

'510    Silence of the Lambs, The (1991)\nName: title, dtype: object'

'510    Silence of the Lambs, The (1991)\nName: title, dtype: object'

'277    Shawshank Redemption, The (1994)\nName: title, dtype: object'

'314    Forrest Gump (1994)\nName: title, dtype: object'

"809    William Shakespeare's Romeo + Juliet (1996)\nName: title, dtype: object"

'43    Seven (a.k.a. Se7en) (1995)\nName: title, dtype: object'

'138    Die Hard: With a Vengeance (1995)\nName: title, dtype: object'

'257    Pulp Fiction (1994)\nName: title, dtype: object'

'395    Firm, The (1993)\nName: title, dtype: object'

'398    Fugitive, The (1993)\nName: title, dtype: object'

'509    Batman (1989)\nName: title, dtype: object'

'1191    George of the Jungle (1997)\nName: title, dtype: object'

'1209    Air Force One (1997)\nName: title, dtype: object'

'1224    Game, The (1997)\nName: title, dtype: object'

'1284    Good Will Hunting (1997)\nName: title, dtype: object'

'1322    As Good as It Gets (1997)\nName: title, dtype: object'

'9    GoldenEye (1995)\nName: title, dtype: object'

'217    Interview with the Vampire: The Vampire Chroni...\nName: title, dtype: object'

'257    Pulp Fiction (1994)\nName: title, dtype: object'

'398    Fugitive, The (1993)\nName: title, dtype: object'

'508    Dances with Wolves (1990)\nName: title, dtype: object'

"591    Heaven's Prisoners (1996)\nName: title, dtype: object"

'869    Return of Martin Guerre, The (Retour de Martin...\nName: title, dtype: object'

'872    Tin Drum, The (Blechtrommel, Die) (1979)\nName: title, dtype: object'

In [25]:
user1 = df.sample()

for col in user1.columns:
  if (user1.iloc[0][col] != 0):
    title = movies_dataset[movies_dataset['movieId'] == col]['title']
    print(title)

recs = nn_recomendations(user1)

0    Toy Story (1995)
Name: title, dtype: object
9    GoldenEye (1995)
Name: title, dtype: object
20    Get Shorty (1995)
Name: title, dtype: object
32    Babe (1995)
Name: title, dtype: object
33    Dead Man Walking (1995)
Name: title, dtype: object
97    Braveheart (1995)
Name: title, dtype: object
116    Birdcage, The (1996)
Name: title, dtype: object
123    Apollo 13 (1995)
Name: title, dtype: object
156    Net, The (1995)
Name: title, dtype: object
192    Disclosure (1994)
Name: title, dtype: object
202    French Kiss (1995)
Name: title, dtype: object
203    Forget Paris (1995)
Name: title, dtype: object
228    Like Water for Chocolate (Como agua para choco...
Name: title, dtype: object
244    Nell (1994)
Name: title, dtype: object
249    Natural Born Killers (1994)
Name: title, dtype: object
251    Once Were Warriors (1994)
Name: title, dtype: object
257    Pulp Fiction (1994)
Name: title, dtype: object
277    Shawshank Redemption, The (1994)
Name: title, dtype: object
287    Sta

1       2       3       4       5       6       7       8       9       \
228    20.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

     10      ...  193565  193567  193571  193573  193579  193581  193583  \
228    10.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

     193585  193587  193609  
228     0.0     0.0     0.0  

[1 rows x 9742 columns]

'Nearest'

array([[228, 403, 608, 178, 506]])

In [26]:
user2 = df.sample()

for col in user2.columns:
  if (user2.iloc[0][col] != 0):
    title = movies_dataset[movies_dataset['movieId'] == col]['title']
    print(title)

recs = nn_recomendations(user2)

0    Toy Story (1995)
Name: title, dtype: object
1    Jumanji (1995)
Name: title, dtype: object
5    Heat (1995)
Name: title, dtype: object
9    GoldenEye (1995)
Name: title, dtype: object
10    American President, The (1995)
Name: title, dtype: object
28    City of Lost Children, The (Cité des enfants p...
Name: title, dtype: object
31    Twelve Monkeys (a.k.a. 12 Monkeys) (1995)
Name: title, dtype: object
40    Mortal Kombat (1995)
Name: title, dtype: object
46    Usual Suspects, The (1995)
Name: title, dtype: object
52    Postman, The (Postino, Il) (1994)
Name: title, dtype: object
93    Bridges of Madison County, The (1995)
Name: title, dtype: object
97    Braveheart (1995)
Name: title, dtype: object
123    Apollo 13 (1995)
Name: title, dtype: object
134    Crimson Tide (1995)
Name: title, dtype: object
201    Ed Wood (1994)
Name: title, dtype: object
208    Farinelli: il castrato (1994)
Name: title, dtype: object
210    Hoop Dreams (1994)
Name: title, dtype: object
224    Star War

1       2       3       4       5       6       7       8       9       \
201    10.0    10.0     0.0     0.0     0.0    20.0     0.0     0.0     0.0   

     10      ...  193565  193567  193571  193573  193579  193581  193583  \
201    10.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

     193585  193587  193609  
201     0.0     0.0     0.0  

[1 rows x 9742 columns]

'Nearest'

array([[201, 230, 179,  53, 493]])